apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30085  # Specify NodePort here
  type: NodePort  # Change service type to NodePort
